// Türkçe

export default {
  /main.ts
    'Open Dictionary View': 'Sözlük Görünümünü Aç',
    'Open Language Switcher': 'Dil Değiştiriciyi Aç',

    //_constants.ts
    'Dictionary': 'Sözlük',

    //customContextMenu.ts
    'Cut': 'Kes',
    'Copy': 'Kopyala',
    'Paste': 'Yapıştır',
    'Show Synonyms': 'Eş Anlamlısını Göster',
    'Look up': 'Sözlükte Ara',

    //settingsTab.ts
    "Reset to default": "Varsayılana Sıfırla",
    'Dictionary Settings': 'Sözlük Ayarları',
    'Language': 'Dil',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': 'Eklentinin Tanımları ve Telaffuzları aramak için kullanacağı Dil.',
    'Synonym Suggestions': 'Eş Anlamlı Kelime Önerileri',
    'Show synonyms for highlighted words': 'Vurgulanan kelimelerin eş anlamlılarını göster',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'Bunu etkinleştirmek, Eklentinin bağlama göre eş anlamlıları daha iyi önermek için tam cümleleri analiz etmesine olanak tanır.',
    'Click ': 'Tıkla ',
    'here': 'buraya',
    ' for Privacy Concerns.': ' Gizlilik Endişeleri için.',
    'Advanced Synonym Search': 'Gelişmiş Eş Anlamlı Arama',
    'Show Options in Context Menu': 'İçerik Menüsünde Seçenekleri Göster',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'Eş anlamlıları aramak (yalnızca otomatik öneriler devre dışıysa) ve Kenar Çubuğunda tam bir tanım aramak için seçeneklerle özel Bağlam Menüsünü etkinleştirin. Uyarı: Bu, Obsidian\'ın varsayılan Bağlam Menüsünü geçersiz kılacaktır.',
    'Click Here': 'Buraya Tıkla',
    'Definition Provider': 'Tanım Sağlayıcı',
    'The API the Plugin will use to search for Definitions.': 'Eklentinin Tanımları aramak için kullanacağı API.',
    'Synonym Provider': 'Eşanlam Sağlayıcı',
    'The API the Plugin will use to search for Synonyms.': 'Eklentinin Eşanlamlıları aramak için kullanacağı API.',
    'More Information': 'Daha fazla bilgi',
    'View Information about the API\'s and the Plugin itself.': 'API\'ler ve Eklentinin kendisi hakkındaki bilgileri görüntüleyin.',
    'More Info': 'Daha fazla bilgi',
    'Donate': 'Bağış',
    'If you like this Plugin, consider donating to support continued development:': 'Bu Eklentiyi beğendiyseniz, sürekli geliştirmeyi desteklemek için bağış yapmayı düşünün:',
    'Local Dictionary Folder': 'Yerel Sözlük Klasörü',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': 'Sözlük tarafından oluşturulan tüm yeni notların yerleştirildiği bir klasör belirtin. Lütfen bu klasörün zaten mevcut olması gerektiğini unutmayın.',
    'Capitalize File Name': 'Dosya Adını Büyük Harf Yap',
    'If you disable this, the names of newly created files will be all lowercase.': 'Bunu devre dışı bırakırsanız, yeni oluşturulan dosyaların adlarının tümü küçük harf olacaktır.',
    'Filename Prefix and Suffix': 'Dosya Adı, Öneki ve Soneki',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'Burada, yeni oluşturduğunuz Dosyalarınız için Önek ve Sonek ekleyebilirsiniz.',
    "Prefix": "Önek",
    "Suffix": "Sonek",
    'Here you can edit the Template for newly created Files.': 'Burada, yeni oluşturulan dosyalar için şablonu düzenleyebilirsiniz.',
    'Click for a List of Variables': 'Değişken listesi için tıklayınız',
    'Template': 'Şablon',
    "Local-Dictionary-Builder Settings": "Yerel Sözlük Oluşturucu Ayarları",
    "Miscellaneous": "Çeşitli",
    "Caching Settings": "Önbelleğe Alma Ayarları",
    "Use Caching": "Önbelleğe Almayı Kullan",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "Önbelleğe almayı etkinleştirin veya devre dışı bırakın. Önbelleğe alma, her sonucu daha sonra kullanmak üzere kaydederek yarı çevrimdışı bir deneyim sağlar.",
    'Here you can delete all cached Data.': 'Burada önbelleğe alınmış tüm verileri silebilirsiniz.',
    "You currently have ": "Şu anda bu kadarına sahipsin: ",
    " cached Definitions and ": " önbelleğe alınmış Tanımlar ve ",
    " cached Synonyms.": " Eş anlamlılar.",
    "Delete Cache": "Önbelleği Sil",
    "Delete": "Sil",
    "Success": "Başarılı",
    'Use Language specific Subfolders': 'Dile özgü alt klasörler kullan',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': 'Her dil için Alt Klasörler oluşturun, örn. "sözlük/tr-TR/Pasta"',


    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Obsidian Dictionary Plugin tarafından otomatik oluşturuldu',
    "Yes, overwrite the old File.": "Evet, eski Dosyanın üzerine yaz.",
    "A existing File with the same Name was found, do you want to overwrite it?": "Aynı isime sahip mevcut bir dosya bulundu, üzerine yazmak istiyor musunuz?",
    "No, keep the old File.": "Hayır, eski Dosyayı sakla.",
    "Meaning {{i}}": "Anlamı {{i}}",


    //infoModal.svelte
    'API Information': 'API Bilgileri',
    'Definition API\'s': 'Tanım API\'leri',
    'Website': 'İnternet sitesi',
    'Synonym API\'s': 'Eşanlamlı Kelime API\'leri',
    'Part of Speech API\'s': 'Konuşma API\'lerinin bir parçası',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'Bu Eklenti <a href="https://feathericons.com/">Feather Icons</a> kullanıyor',

    //dictionaryView.svelte
    'Enter a word': 'Bir kelime girin',
    "Clear": "Temizle",
    "Change Language": "Dili Değiştir",
    "Change Provider": "Sağlayıcıyı Değiştir",
    "Collapse Results": "Sonuçları Daralt",
    'Pronunciation': 'Telaffuz',
    'Meanings': 'Anlamı/ları',
    "Origin": "kökeni",
    'New Note': 'Yeni Not',
    "View Error": "Hatayı Görüntüle",
    "Match Case": "Durumları Eşleştir",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\" panoya kopyalandı",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': 'Aradığınız kelimeyi bulamıyorum veya sunucuya ulaşılamıyor. Birkaç dakika sonra tekrar deneyebilirsiniz.',

    //meaningComponent.ts
    'Definition:': 'Tanım:',
    'Synonyms:': 'Eş anlamlı:',
    'Antonyms:': 'Zıt anlamlı:',

    //modals
    "Choose a Definition Provider Service": "Bir Tanım Sağlayıcı Hizmeti Seçin",
    "Choose a Language": "Bir Dil Seçin",
    "Choose a Synonym Provider Service": "Bir Eşanlamlı Kelime Sağlayıcı Hizmeti Seçin",
};
